version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - echo Front Build start
      - npm run build
      - echo Front Build end
